title: Obsidian notes
encoding: utf-8
markdown: GitHub

include:
  - '**/*.md'

exclude:
  - .git
  - node_modules
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-relative-links

# permalink: pretty
theme: jekyll-theme-minimal
highlighter: rouge
relative_links:
  enabled: true
  collections: true
